site_name: SuMiTB マイクロサービスブートキャンプ

theme:
  name: material
  language: ja
  logo: images/aws_smile_logo.png
  palette:
    primary: black

copyright: © 2023, Amazon Web Services, Inc. or its affiliates. All rights reserved.

plugins:
  - search:
      lang: ja
  - markdownextradata: {}
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 95%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - fontawesome_markdown

extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

use_directory_urls: false
